version: "3.7"

services:
    php-fpm:
        container_name: "${APP_NAME}_APPLICATION"
        build:
            context: .
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
                - DB_PROD_HOST
                - DB_PROD_PORT=${DB_PROD_PORT:-3306}
                - SSH_PROD_USER
                - SSH_PROD_SERVER
                - SSH_MYSQL_FORWARD_PORT=${SSH_MYSQL_FORWARD_PORT:-3307}
        user: "1000:1000"
        restart: unless-stopped
        networks:
            - default_network
        volumes:
            - ./:/var/www/html
            - ./config/php/php.ini:/usr/local/etc/php/php.ini

    nginx:
        tty: true
        image: nginx:alpine
        container_name: "${APP_NAME}_NGINX"
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        networks:
            - default_network
        volumes:
            - ./:/var/www/html
            - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

    db:
        container_name: "${APP_NAME}_DB"
        image: mariadb
        restart: unless-stopped
        environment:
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
        ports:
            - 3306:3306
        networks:
            - default_network
        volumes:
            - data_volume:/var/lib/mysql

    cache:
        container_name: "${APP_NAME}_REDIS"
        image: redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - default_network

    phpmyadmin:
        container_name: "${APP_NAME}_PHPMYADMIN"
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 8080:80
        networks:
            - default_network
        environment:
            - PMA_ARBITRARY=1
            - UPLOAD_LIMIT=350M
            - PMA_HOST=mariadb

volumes:
    data_volume:
        driver: local
networks:
    default_network:
        driver: bridge
