name: CI Pipeline

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  check-application:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-18-218-29-206.us-east-2.compute.amazonaws.com 'cd cms-filament && git pull origin master && 
            sudo docker exec Filament-CMS_APPLICATION npm run build &&
            sudo docker exec Filament-CMS_APPLICATION php artisan migrate'
